# Generated by Django 5.0.6 on 2024-09-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='Todo',
        ),
    ]
